[package]
name = "r-fast-copy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="test_gen"
path="src/test_gen.rs"

[dependencies]
futures = "0.3"
rand="0.8"